STUDY_NAME : "Wednesday-002"

competencia01:
  DATA_PATH: "data/competencia_01_crudo_filtrado.csv"
  SEMILLA: [100001, 200002, 300003, 400004, 500005]
  MES_TRAIN: [202101, 202102]
  MES_VALIDACION: [202103]
  MES_TEST: [202104]
  GANANCIA_ACIERTO: 780000
  COSTO_ESTIMULO: 20000
  FINAL_TRAIN: [202101, 202102, 202103, 202104]
  FINAL_PREDICT: [202106]

parametros_lgb:
  n_trials: 100
  num_leaves: [10, 300]
  learning_rate: [0.01, 0.3]
  feature_fraction: [0.4, 1.0]
  bagging_fraction: [0.4, 1.0]
  min_data_in_leaf: [50, 100, 200]
  max_depth: [3, 15]
  lambda_l1: [0.0, 10.0]
  lambda_l2: [0.0, 10.0]
  bin : [30, 31]